### ISSUE TITLE
RuntimeError: Unsupported image type, must be 8bit gray or RGB image.

### ISSUE THREAD

**Issue by anubhav1997** [danmohaha/CVPRW2019_Face_Artifacts#11]
Keep running into this issue with every image that I have tried. 

Loading checkpoint /home/anubhav/CVPRW2019_Face_Artifacts/ckpt_res50/model
Testing: ./jpg/i056sa-mn.jpg
Traceback (most recent call last):
  File "demo.py", line 120, in <module>
    run(args.input_dir)
  File "demo.py", line 88, in run
    prob = im_test(im)
  File "demo.py", line 47, in im_test
    face_info = lib.align(im[:, :, (2,1,0)], front_face_detector, lmark_predictor)
  File "/home/anubhav/CVPRW2019_Face_Artifacts/py_utils/face_utils/lib.py", line 231, in align
    faces = face_detector(im, scale)
RuntimeError: Unsupported image type, must be 8bit gray or RGB image.

**Comment by hassanjardali** [comment]
Hello Sir, but how you did solve this issue ?
